services:
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    container_name: postgres-order-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lucas@36
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-order-management
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget -qO- http://app:3000/v1/health || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 5
volumes:
  postgres-data:
